# Generated by Django 5.2.3 on 2025-06-28 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('example', '0001_initial'),
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='word.word'),
        ),
    ]
