# Generated by Django 5.2.3 on 2025-07-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_validation_minutes', models.IntegerField(default=2)),
                ('new_word_day_duration', models.IntegerField(default=7)),
            ],
        ),
    ]
