# Generated by Django 5.2.3 on 2025-08-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_settings_new_word_day_duration_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='words_default_complexity_level',
            field=models.IntegerField(default=0),
        ),
    ]
