# Generated by Django 5.2.3 on 2025-08-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_usersettings_words_default_complexity_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='words_default_complexity_level',
        ),
    ]
