# Generated by Django 5.2.3 on 2025-08-22 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_remove_usersettings_words_default_complexity_level'),
        ('word', '0002_complexitylevel_is_complexity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='words_default_complexity_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='word.complexitylevel'),
        ),
    ]
