# Generated by Django 5.2.3 on 2025-08-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_usersettings_words_default_complexity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='blind_test_score_to_change_complexity_level',
            field=models.IntegerField(default=20),
        ),
    ]
