# Generated by Django 5.2.3 on 2025-07-23 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passage', '0001_initial'),
        ('word', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by_passage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passageword',
            name='passage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passage_words', to='passage.passage'),
        ),
        migrations.AddField(
            model_name='passageword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_passages', to='word.word'),
        ),
        migrations.AddField(
            model_name='userpassage',
            name='passage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passage_users', to='passage.passage'),
        ),
        migrations.AddField(
            model_name='userpassage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_passages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpassageshareonly',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_audiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpassageshareonly',
            name='user_passage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_user_passages', to='passage.userpassage'),
        ),
        migrations.AlterUniqueTogether(
            name='passageword',
            unique_together={('word', 'passage')},
        ),
        migrations.AlterUniqueTogether(
            name='userpassage',
            unique_together={('user', 'passage')},
        ),
        migrations.AlterUniqueTogether(
            name='userpassageshareonly',
            unique_together={('user_passage', 'user')},
        ),
    ]
