# Generated by Django 5.2.3 on 2025-07-23 18:50

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpassage',
            name='note',
            field=django_ckeditor_5.fields.CKEditor5Field(default='note'),
            preserve_default=False,
        ),
    ]
