# Generated by Django 5.2.3 on 2025-07-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0003_userpassage_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpassage',
            name='hide_from_mine_profile',
            field=models.BooleanField(default=False),
        ),
    ]
