# Generated by Django 5.2.3 on 2025-06-28 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0003_passage_added_by_alter_passage_content'),
        ('word', '0002_remove_word_passage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passageword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passage_words', to='passage.passage')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_passages', to='word.word')),
            ],
        ),
    ]
