# Generated by Django 5.2.3 on 2025-08-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0004_userpassage_hide_from_mine_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='IeltsBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
