# Generated by Django 5.2.3 on 2025-06-30 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0004_passageword'),
        ('word', '0006_alter_word_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='passageword',
            constraint=models.UniqueConstraint(fields=('word', 'passage'), name='passageword_word_passage'),
        ),
        migrations.AddConstraint(
            model_name='userpassage',
            constraint=models.UniqueConstraint(fields=('user', 'passage'), name='passageword_user_passage'),
        ),
    ]
