# Generated by Django 5.2.3 on 2025-08-08 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0005_ieltsbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='ielts_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ielts_book_passage', to='passage.ieltsbook'),
        ),
    ]
