# Generated by Django 5.2.3 on 2025-07-19 05:00

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0005_passageword_passageword_word_passage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpassage',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='nothing'),
            preserve_default=False,
        ),
    ]
