# Generated by Django 5.2.3 on 2025-07-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0006_userpassage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpassage',
            name='title',
            field=models.CharField(default='text', max_length=100),
            preserve_default=False,
        ),
    ]
