# Generated by Django 5.2.3 on 2025-09-24 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
        ('passage', '0006_passage_ielts_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassageNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_passages', to='note.note')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passage_notes', to='passage.passage')),
            ],
            options={
                'unique_together': {('note', 'passage')},
            },
        ),
    ]
