# Generated by Django 5.2.3 on 2025-07-22 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0007_userpassage_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPassageShareOnly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='passageword',
            name='passageword_word_passage',
        ),
        migrations.RemoveConstraint(
            model_name='userpassage',
            name='passageword_user_passage',
        ),
        migrations.AddField(
            model_name='userpassage',
            name='share_to_user',
            field=models.CharField(choices=[('Public', 'Public'), ('Friend', 'Friend'), ('Custom', 'Custom'), ('Private', 'Private')], default='Public', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpassageshareonly',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpassageshareonly',
            name='user_passage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_user_passages', to='passage.userpassage'),
        ),
        migrations.AlterUniqueTogether(
            name='userpassageshareonly',
            unique_together={('user_passage', 'user')},
        ),
    ]
