# Generated by Django 5.2.3 on 2025-07-22 14:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0008_userpassageshareonly_and_more'),
        ('word', '0008_alter_userword_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='passageword',
            unique_together={('word', 'passage')},
        ),
        migrations.AlterUniqueTogether(
            name='userpassage',
            unique_together={('user', 'passage')},
        ),
    ]
