# Generated by Django 5.2.3 on 2025-08-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complexitylevel',
            name='is_complexity_level',
            field=models.BooleanField(default=False),
        ),
    ]
