# Generated by Django 5.2.3 on 2025-06-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='passage',
        ),
    ]
