# Generated by Django 5.2.3 on 2025-08-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_complexitylevel_is_complexity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='blind_test_score',
            field=models.IntegerField(default=0),
        ),
    ]
