# Generated by Django 5.2.3 on 2025-06-29 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_userword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userword',
            constraint=models.UniqueConstraint(fields=('user', 'word'), name='userword_user_word'),
        ),
    ]
