# Generated by Django 5.2.3 on 2025-06-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_userword_userword_user_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
