# Generated by Django 5.2.3 on 2025-07-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0006_alter_word_text'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userword',
            name='userword_user_word',
        ),
    ]
