# Generated by Django 5.2.3 on 2025-07-22 14:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0007_remove_userword_userword_user_word'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userword',
            unique_together={('user', 'word')},
        ),
    ]
