# Generated by Django 5.2.3 on 2025-06-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userfriend'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfriend',
            constraint=models.UniqueConstraint(fields=('user', 'friend'), name='userfriend_user_friend'),
        ),
    ]
