# Generated by Django 5.2.3 on 2025-08-18 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
