# Generated by Django 5.2.3 on 2025-08-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('General', 'General')], default='General', max_length=20),
        ),
    ]
