# Generated by Django 5.2.3 on 2025-06-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='status',
        ),
    ]
