# Generated by Django 5.2.3 on 2025-07-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_friendrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='request_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
