# Generated by Django 5.2.3 on 2025-07-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_friendrequest_request_message'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendrequest',
            name='friendrequest_user_requested_to',
        ),
        migrations.RemoveConstraint(
            model_name='userfriend',
            name='userfriend_user_friend',
        ),
    ]
