# Generated by Django 5.2.3 on 2025-07-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_friendrequest_friendrequest_user_requested_to_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('user', 'requested_to')},
        ),
        migrations.AlterUniqueTogether(
            name='userfriend',
            unique_together={('user', 'friend')},
        ),
    ]
